// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdvm5ijsrV2cgR5uyQ3VmeX3QeKRWeInY',
    appId: '1:813587709403:web:083308f693c9770790bbfe',
    messagingSenderId: '813587709403',
    projectId: 'newsletter-63e04',
    authDomain: 'newsletter-63e04.firebaseapp.com',
    storageBucket: 'newsletter-63e04.firebasestorage.app',
    measurementId: 'G-D5FX9LW2DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4bDqx7D2VXlz6DjgmdIMxGrL8ttF504M',
    appId: '1:813587709403:android:84fa06150a63cd5590bbfe',
    messagingSenderId: '813587709403',
    projectId: 'newsletter-63e04',
    storageBucket: 'newsletter-63e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAxwnOm1WX5s7zFlZEhqx01Ct-xPyxEw8',
    appId: '1:813587709403:ios:2d5fefc86d4cea2f90bbfe',
    messagingSenderId: '813587709403',
    projectId: 'newsletter-63e04',
    storageBucket: 'newsletter-63e04.firebasestorage.app',
    iosBundleId: 'com.example.updateLatest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAxwnOm1WX5s7zFlZEhqx01Ct-xPyxEw8',
    appId: '1:813587709403:ios:2d5fefc86d4cea2f90bbfe',
    messagingSenderId: '813587709403',
    projectId: 'newsletter-63e04',
    storageBucket: 'newsletter-63e04.firebasestorage.app',
    iosBundleId: 'com.example.updateLatest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdvm5ijsrV2cgR5uyQ3VmeX3QeKRWeInY',
    appId: '1:813587709403:web:d6ea58b1348e1b9e90bbfe',
    messagingSenderId: '813587709403',
    projectId: 'newsletter-63e04',
    authDomain: 'newsletter-63e04.firebaseapp.com',
    storageBucket: 'newsletter-63e04.firebasestorage.app',
    measurementId: 'G-EHTP6V2EE7',
  );
}
